/**
 * Mock temporário para preview visual da nova página de detalhes.
 * ============================================================================
 * Remover após aprovação — na fase de conexão, `initialAcordo` virá do
 * service real (buscarAcordoPorId) via [id]/page.tsx.
 * ============================================================================
 */

import type { AcordoComParcelas } from '../../domain';

export const MOCK_ACORDO: AcordoComParcelas = {
  id: 46,
  processoId: 12345,
  tipo: 'acordo',
  direcao: 'recebimento',
  valorTotal: 12600,
  dataVencimentoPrimeiraParcela: '2026-04-30',
  status: 'pago_parcial',
  numeroParcelas: 6,
  formaDistribuicao: 'integral',
  percentualEscritorio: 30,
  percentualCliente: 70,
  honorariosSucumbenciaisTotal: 1800,
  observacoes:
    'Acordo homologado em audiência. Cliente optou por recebimento em 6 parcelas mensais iguais. Primeira parcela via depósito judicial, demais por transferência direta.',
  createdAt: '2026-04-09T10:30:00.000Z',
  updatedAt: '2026-04-15T14:22:00.000Z',
  createdBy: null,
  totalParcelas: 6,
  parcelasPagas: 2,
  parcelasPendentes: 4,
  proximoVencimento: '2026-06-30',
  processo: {
    id: 12345,
    trt: 'TRT3',
    grau: '1',
    numero_processo: '0010249-69.2026.5.03.0105',
    classe_judicial: 'ATSum',
    descricao_orgao_julgador: '26ª VARA DO TRABALHO DE BELO HORIZONTE',
    nome_parte_autora: 'KARINE BRAGANCA REIS',
    nome_parte_re: 'O NOVO CAMPEAO LTDA',
  },
  parcelas: [
    {
      id: 1001,
      acordoCondenacaoId: 46,
      numeroParcela: 1,
      valorBrutoCreditoPrincipal: 2100,
      honorariosContratuais: 630,
      honorariosSucumbenciais: 300,
      valorRepasseCliente: 1470,
      dataVencimento: '2026-04-30',
      dataEfetivacao: '2026-04-30',
      status: 'recebida',
      formaPagamento: 'deposito_judicial',
      statusRepasse: 'repassado',
      editadoManualmente: false,
      declaracaoPrestacaoContasUrl: '/mock/declaracao-1.pdf',
      dataDeclaracaoAnexada: '2026-05-02',
      comprovanteRepasseUrl: '/mock/comprovante-1.pdf',
      dataRepasse: '2026-05-03',
      usuarioRepasseId: 1,
      arquivoQuitacaoReclamante: null,
      dataQuitacaoAnexada: null,
      createdAt: '2026-04-09T10:30:00.000Z',
      updatedAt: '2026-05-03T12:00:00.000Z',
      dadosPagamento: null,
    },
    {
      id: 1002,
      acordoCondenacaoId: 46,
      numeroParcela: 2,
      valorBrutoCreditoPrincipal: 2100,
      honorariosContratuais: 630,
      honorariosSucumbenciais: 300,
      valorRepasseCliente: 1470,
      dataVencimento: '2026-05-30',
      dataEfetivacao: '2026-05-30',
      status: 'recebida',
      formaPagamento: 'transferencia_direta',
      statusRepasse: 'pendente_transferencia',
      editadoManualmente: false,
      declaracaoPrestacaoContasUrl: '/mock/declaracao-2.pdf',
      dataDeclaracaoAnexada: '2026-05-31',
      comprovanteRepasseUrl: null,
      dataRepasse: null,
      usuarioRepasseId: null,
      arquivoQuitacaoReclamante: null,
      dataQuitacaoAnexada: null,
      createdAt: '2026-04-09T10:30:00.000Z',
      updatedAt: '2026-05-31T09:00:00.000Z',
      dadosPagamento: null,
    },
    {
      id: 1003,
      acordoCondenacaoId: 46,
      numeroParcela: 3,
      valorBrutoCreditoPrincipal: 2100,
      honorariosContratuais: 630,
      honorariosSucumbenciais: 300,
      valorRepasseCliente: 1470,
      dataVencimento: '2026-06-30',
      dataEfetivacao: null,
      status: 'pendente',
      formaPagamento: null,
      statusRepasse: 'nao_aplicavel',
      editadoManualmente: false,
      declaracaoPrestacaoContasUrl: null,
      dataDeclaracaoAnexada: null,
      comprovanteRepasseUrl: null,
      dataRepasse: null,
      usuarioRepasseId: null,
      arquivoQuitacaoReclamante: null,
      dataQuitacaoAnexada: null,
      createdAt: '2026-04-09T10:30:00.000Z',
      updatedAt: '2026-04-09T10:30:00.000Z',
      dadosPagamento: null,
    },
    {
      id: 1004,
      acordoCondenacaoId: 46,
      numeroParcela: 4,
      valorBrutoCreditoPrincipal: 2100,
      honorariosContratuais: 630,
      honorariosSucumbenciais: 300,
      valorRepasseCliente: 1470,
      dataVencimento: '2026-07-30',
      dataEfetivacao: null,
      status: 'pendente',
      formaPagamento: null,
      statusRepasse: 'nao_aplicavel',
      editadoManualmente: false,
      declaracaoPrestacaoContasUrl: null,
      dataDeclaracaoAnexada: null,
      comprovanteRepasseUrl: null,
      dataRepasse: null,
      usuarioRepasseId: null,
      arquivoQuitacaoReclamante: null,
      dataQuitacaoAnexada: null,
      createdAt: '2026-04-09T10:30:00.000Z',
      updatedAt: '2026-04-09T10:30:00.000Z',
      dadosPagamento: null,
    },
    {
      id: 1005,
      acordoCondenacaoId: 46,
      numeroParcela: 5,
      valorBrutoCreditoPrincipal: 2100,
      honorariosContratuais: 630,
      honorariosSucumbenciais: 300,
      valorRepasseCliente: 1470,
      dataVencimento: '2026-08-30',
      dataEfetivacao: null,
      status: 'pendente',
      formaPagamento: null,
      statusRepasse: 'nao_aplicavel',
      editadoManualmente: false,
      declaracaoPrestacaoContasUrl: null,
      dataDeclaracaoAnexada: null,
      comprovanteRepasseUrl: null,
      dataRepasse: null,
      usuarioRepasseId: null,
      arquivoQuitacaoReclamante: null,
      dataQuitacaoAnexada: null,
      createdAt: '2026-04-09T10:30:00.000Z',
      updatedAt: '2026-04-09T10:30:00.000Z',
      dadosPagamento: null,
    },
    {
      id: 1006,
      acordoCondenacaoId: 46,
      numeroParcela: 6,
      valorBrutoCreditoPrincipal: 2100,
      honorariosContratuais: 630,
      honorariosSucumbenciais: 300,
      valorRepasseCliente: 1470,
      dataVencimento: '2026-09-30',
      dataEfetivacao: null,
      status: 'pendente',
      formaPagamento: null,
      statusRepasse: 'nao_aplicavel',
      editadoManualmente: false,
      declaracaoPrestacaoContasUrl: null,
      dataDeclaracaoAnexada: null,
      comprovanteRepasseUrl: null,
      dataRepasse: null,
      usuarioRepasseId: null,
      arquivoQuitacaoReclamante: null,
      dataQuitacaoAnexada: null,
      createdAt: '2026-04-09T10:30:00.000Z',
      updatedAt: '2026-04-09T10:30:00.000Z',
      dadosPagamento: null,
    },
  ],
};
