-- CHAT CALLS FEATURE
-- Tabelas para gerenciamento de chamadas de áudio/vídeo e histórico

-- ENUMS já existem ou vamos usar constraints de texto para simplicidade e compatibilidade com domain

-- Tabela de Chamadas
CREATE TABLE IF NOT EXISTS chamadas (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    meeting_id TEXT NOT NULL, -- ID do Dyte ou similar
    sala_id BIGINT NOT NULL REFERENCES salas_chat(id) ON DELETE CASCADE,
    tipo TEXT NOT NULL CHECK (tipo IN ('audio', 'video')),
    iniciado_por BIGINT NOT NULL REFERENCES usuarios(id),
    status TEXT NOT NULL CHECK (status IN ('iniciada', 'em_andamento', 'finalizada', 'cancelada', 'recusada')),
    iniciada_em TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    finalizada_em TIMESTAMPTZ,
    duracao_segundos INTEGER,
    transcricao TEXT,
    resumo TEXT,
    gravacao_url TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- Tabela de Participantes da Chamada
CREATE TABLE IF NOT EXISTS chamadas_participantes (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    chamada_id BIGINT NOT NULL REFERENCES chamadas(id) ON DELETE CASCADE,
    usuario_id BIGINT NOT NULL REFERENCES usuarios(id) ON DELETE CASCADE,
    entrou_em TIMESTAMPTZ,
    saiu_em TIMESTAMPTZ,
    duracao_segundos INTEGER,
    aceitou BOOLEAN, -- null = pendente, true = aceitou, false = recusou
    respondeu_em TIMESTAMPTZ,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    UNIQUE(chamada_id, usuario_id)
);

-- Índices para performance
CREATE INDEX IF NOT EXISTS idx_chamadas_sala_id ON chamadas(sala_id);
CREATE INDEX IF NOT EXISTS idx_chamadas_iniciado_por ON chamadas(iniciado_por);
CREATE INDEX IF NOT EXISTS idx_chamadas_status ON chamadas(status);
CREATE INDEX IF NOT EXISTS idx_chamadas_iniciada_em ON chamadas(iniciada_em);
CREATE UNIQUE INDEX IF NOT EXISTS idx_chamadas_meeting_id ON chamadas(meeting_id);

CREATE INDEX IF NOT EXISTS idx_chamadas_participantes_chamada_id ON chamadas_participantes(chamada_id);
CREATE INDEX IF NOT EXISTS idx_chamadas_participantes_usuario_id ON chamadas_participantes(usuario_id);

-- RLS Policies
ALTER TABLE chamadas ENABLE ROW LEVEL SECURITY;
ALTER TABLE chamadas_participantes ENABLE ROW LEVEL SECURITY;

-- Chamadas Policies
CREATE POLICY "Usuários podem ver chamadas que iniciaram ou participam"
    ON chamadas FOR SELECT
    USING (
        auth.uid() = iniciado_por OR
        EXISTS (
            SELECT 1 FROM chamadas_participantes cp
            WHERE cp.chamada_id = chamadas.id AND cp.usuario_id = auth.uid()
        )
        OR 
        -- Também permitir se for membro da sala (para histórico)
        EXISTS (
            SELECT 1 FROM salas_chat sc
            WHERE sc.id = chamadas.sala_id AND (
                sc.criado_por = auth.uid() OR 
                sc.participante_id = auth.uid() OR
                sc.tipo = 'geral' -- Se for geral, todos veem
            )
        )
    );

CREATE POLICY "Usuários podem criar chamadas"
    ON chamadas FOR INSERT
    WITH CHECK (auth.uid() = iniciado_por);

CREATE POLICY "Participantes podem atualizar chamadas"
    ON chamadas FOR UPDATE
    USING (
        auth.uid() = iniciado_por OR
        EXISTS (
            SELECT 1 FROM chamadas_participantes cp
            WHERE cp.chamada_id = chamadas.id AND cp.usuario_id = auth.uid()
        )
    );

-- Participantes Policies
CREATE POLICY "Usuários podem ver participantes de chamadas que têm acesso"
    ON chamadas_participantes FOR SELECT
    USING (
        EXISTS (
            SELECT 1 FROM chamadas c
            WHERE c.id = chamadas_participantes.chamada_id AND (
                c.iniciado_por = auth.uid() OR
                EXISTS (
                    SELECT 1 FROM chamadas_participantes cp
                    WHERE cp.chamada_id = c.id AND cp.usuario_id = auth.uid()
                )
            )
        )
    );

CREATE POLICY "Sistema/Iniciador pode adicionar participantes"
    ON chamadas_participantes FOR INSERT
    WITH CHECK (
        EXISTS (
            SELECT 1 FROM chamadas c
            WHERE c.id = chamada_id AND c.iniciado_por = auth.uid()
        ) OR usuario_id = auth.uid() -- Auto-entrar
    );

CREATE POLICY "Participantes podem atualizar seus próprios status"
    ON chamadas_participantes FOR UPDATE
    USING (usuario_id = auth.uid());
