-- CHAT CALLS FEATURE
-- Tabelas para gerenciamento de chamadas de áudio/vídeo e histórico

-- ENUMS já existem ou vamos usar constraints de texto para simplicidade e compatibilidade com domain

-- Tabela de Chamadas
CREATE TABLE IF NOT EXISTS chamadas (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    meeting_id TEXT NOT NULL, -- ID do Dyte ou similar
    sala_id BIGINT NOT NULL REFERENCES salas_chat(id) ON DELETE CASCADE,
    tipo TEXT NOT NULL CHECK (tipo IN ('audio', 'video')),
    iniciado_por BIGINT NOT NULL REFERENCES usuarios(id),
    status TEXT NOT NULL CHECK (status IN ('iniciada', 'em_andamento', 'finalizada', 'cancelada', 'recusada')),
    iniciada_em TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    finalizada_em TIMESTAMPTZ,
    duracao_segundos INTEGER,
    transcricao TEXT,
    resumo TEXT,
    gravacao_url TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- Tabela de Participantes da Chamada
CREATE TABLE IF NOT EXISTS chamadas_participantes (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    chamada_id BIGINT NOT NULL REFERENCES chamadas(id) ON DELETE CASCADE,
    usuario_id BIGINT NOT NULL REFERENCES usuarios(id) ON DELETE CASCADE,
    entrou_em TIMESTAMPTZ,
    saiu_em TIMESTAMPTZ,
    duracao_segundos INTEGER,
    aceitou BOOLEAN, -- null = pendente, true = aceitou, false = recusou
    respondeu_em TIMESTAMPTZ,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    UNIQUE(chamada_id, usuario_id)
);

-- Índices para performance
CREATE INDEX IF NOT EXISTS idx_chamadas_sala_id ON chamadas(sala_id);
CREATE INDEX IF NOT EXISTS idx_chamadas_iniciado_por ON chamadas(iniciado_por);
CREATE INDEX IF NOT EXISTS idx_chamadas_status ON chamadas(status);
CREATE INDEX IF NOT EXISTS idx_chamadas_iniciada_em ON chamadas(iniciada_em);
CREATE UNIQUE INDEX IF NOT EXISTS idx_chamadas_meeting_id ON chamadas(meeting_id);

CREATE INDEX IF NOT EXISTS idx_chamadas_participantes_chamada_id ON chamadas_participantes(chamada_id);
CREATE INDEX IF NOT EXISTS idx_chamadas_participantes_usuario_id ON chamadas_participantes(usuario_id);
-- Índice composto para otimizar políticas RLS
CREATE INDEX IF NOT EXISTS idx_chamadas_participantes_usuario_id_chamada_id ON chamadas_participantes(usuario_id, chamada_id);
-- Índice composto para otimizar verificação de iniciador e sala
CREATE INDEX IF NOT EXISTS idx_chamadas_iniciado_por_sala_id ON chamadas(iniciado_por, sala_id);

-- ============================================================================
-- FUNÇÃO HELPER: Verifica se usuário é participante (bypass RLS para evitar recursão)
-- ============================================================================
-- Esta função usa SECURITY DEFINER para executar com privilégios elevados,
-- permitindo consultar chamadas_participantes sem acionar RLS e quebrar ciclos de recursão
CREATE OR REPLACE FUNCTION public.user_is_chamada_participant(
    p_chamada_id BIGINT,
    p_usuario_id BIGINT
)
RETURNS BOOLEAN
LANGUAGE SQL
SECURITY DEFINER
SET search_path = ''
STABLE
AS $$
    SELECT EXISTS (
        SELECT 1
        FROM public.chamadas_participantes
        WHERE chamada_id = p_chamada_id
        AND usuario_id = p_usuario_id
    );
$$;

COMMENT ON FUNCTION public.user_is_chamada_participant IS
    'Verifica se um usuário é participante de uma chamada. Usa SECURITY DEFINER para bypass RLS e evitar recursão infinita em políticas RLS.';

-- RLS Policies
ALTER TABLE chamadas ENABLE ROW LEVEL SECURITY;
ALTER TABLE chamadas_participantes ENABLE ROW LEVEL SECURITY;

-- Chamadas Policies
-- NOTA: Usa função helper para evitar recursão infinita com chamadas_participantes
CREATE POLICY "Usuários podem ver chamadas que iniciaram ou participam"
    ON chamadas FOR SELECT
    TO authenticated
    USING (
        (SELECT get_current_user_id()) = iniciado_por OR
        public.user_is_chamada_participant(chamadas.id, (SELECT get_current_user_id())) OR
        -- Também permitir se for membro da sala (para histórico)
        EXISTS (
            SELECT 1 FROM salas_chat sc
            WHERE sc.id = chamadas.sala_id AND (
                sc.criado_por = (SELECT get_current_user_id()) OR 
                sc.participante_id = (SELECT get_current_user_id()) OR
                sc.tipo = 'geral' -- Se for geral, todos veem
            )
        )
    );

CREATE POLICY "Usuários podem criar chamadas"
    ON chamadas FOR INSERT
    TO authenticated
    WITH CHECK ((SELECT get_current_user_id()) = iniciado_por);

CREATE POLICY "Participantes podem atualizar chamadas"
    ON chamadas FOR UPDATE
    TO authenticated
    USING (
        (SELECT get_current_user_id()) = iniciado_por OR
        public.user_is_chamada_participant(chamadas.id, (SELECT get_current_user_id()))
    );

-- Participantes Policies
-- NOTA: Usa verificações diretas sem depender de políticas RLS de chamadas
-- para evitar recursão infinita
CREATE POLICY "Usuários podem ver participantes de chamadas que têm acesso"
    ON chamadas_participantes FOR SELECT
    TO authenticated
    USING (
        -- Se o usuário é o próprio participante, pode ver
        usuario_id = (SELECT get_current_user_id()) OR
        -- Se o usuário iniciou a chamada (verificação direta na tabela, bypass RLS)
        EXISTS (
            SELECT 1 FROM public.chamadas c
            WHERE c.id = chamadas_participantes.chamada_id 
            AND c.iniciado_por = (SELECT get_current_user_id())
        ) OR
        -- Se o usuário é membro da sala (verificação direta, bypass RLS)
        EXISTS (
            SELECT 1 FROM public.chamadas c
            JOIN public.salas_chat sc ON sc.id = c.sala_id
            WHERE c.id = chamadas_participantes.chamada_id
            AND (
                sc.criado_por = (SELECT get_current_user_id()) OR
                sc.participante_id = (SELECT get_current_user_id()) OR
                sc.tipo = 'geral'
            )
        )
    );

CREATE POLICY "Sistema/Iniciador pode adicionar participantes"
    ON chamadas_participantes FOR INSERT
    TO authenticated
    WITH CHECK (
        EXISTS (
            SELECT 1 FROM public.chamadas c
            WHERE c.id = chamada_id AND c.iniciado_por = (SELECT get_current_user_id())
        ) OR usuario_id = (SELECT get_current_user_id()) -- Auto-entrar
    );

CREATE POLICY "Participantes podem atualizar seus próprios status"
    ON chamadas_participantes FOR UPDATE
    TO authenticated
    USING (usuario_id = (SELECT get_current_user_id()));
