/**
 * debug-login-multi-trts.ts
 *
 * Verifica se os TRTs que estão falhando em produção também falham:
 * (a) Localmente, com chromium local
 * (b) Remotamente, conectado ao browser remoto da Cloudron
 *
 * Para cada TRT testa apenas o GET inicial em login.seam e analisa:
 *   - HTTP status do response final
 *   - Title da página
 *   - Headers de bloqueio (Server, Via, X-Cache, X-Amz-Cf-*)
 *   - Presença do #btnSsoPdpj
 *
 * Se LOCAL passa mas REMOTO falha → confirma bloqueio por IP do servidor browser.
 * Se AMBOS falham com mesmo title → bloqueio no User-Agent / Accept / Sec-Fetch.
 * Se LOCAL falha → tribunal está realmente fora.
 *
 * Uso:
 *   npx tsx scripts/captura/pendentes/debug-login-multi-trts.ts          # ambos modos
 *   npx tsx scripts/captura/pendentes/debug-login-multi-trts.ts --modo=local
 *   npx tsx scripts/captura/pendentes/debug-login-multi-trts.ts --modo=remoto
 *
 * Saída: test-expedientes/<ts>_multi-trts_relatorio.json
 */

import { config } from 'dotenv';
import { resolve } from 'path';
config({ path: resolve(process.cwd(), '.env.local') });
config();

import * as fs from 'node:fs';
import * as path from 'node:path';
import { chromium, type Browser, type BrowserContext } from 'playwright';

// TRTs com erro WAF/CDN na captura ID 3124 (5/5 14:16):
const TRTS_PROBLEMATICOS = ['TRT2', 'TRT5', 'TRT7', 'TRT14', 'TRT17', 'TRT21'];
// Controles (passaram OK na mesma execução): TRT1 e TRT3
const TRTS_CONTROLE = ['TRT1', 'TRT3'];

const TODOS_TRTS = [...TRTS_PROBLEMATICOS, ...TRTS_CONTROLE];

const args = process.argv.slice(2);
const modoArg = args.find((a) => a.startsWith('--modo='))?.split('=')[1];
const MODOS: ('local' | 'remoto')[] =
  modoArg === 'local' ? ['local'] : modoArg === 'remoto' ? ['remoto'] : ['local', 'remoto'];

const OUTPUT_DIR = path.join(process.cwd(), 'test-expedientes');
if (!fs.existsSync(OUTPUT_DIR)) fs.mkdirSync(OUTPUT_DIR, { recursive: true });
const RUN_TS = new Date().toISOString().replace(/[:.]/g, '-');

interface ResultadoTRT {
  trt: string;
  modo: 'local' | 'remoto';
  loginUrl: string;
  urlFinal: string;
  status: number | null;
  title: string;
  headers: Record<string, string>;
  bodyTrecho: string;
  temBtnSso: boolean;
  ehBloqueio: boolean;
  origemBloqueio?: string;
  erro?: string;
  duracaoMs: number;
}

function log(msg: string) {
  console.log(`[${new Date().toISOString().slice(11, 19)}] ${msg}`);
}

async function testarTRTNoContexto(
  ctx: BrowserContext,
  trt: string,
  modo: 'local' | 'remoto',
): Promise<ResultadoTRT> {
  const loginUrl = `https://pje.${trt.toLowerCase()}.jus.br/primeirograu/login.seam`;
  const inicio = Date.now();
  const page = await ctx.newPage();

  // Anti-detecção mínima (igual produção)
  await page.addInitScript(() => {
    Object.defineProperty(navigator, 'webdriver', { get: () => false });
    Object.defineProperty(navigator, 'plugins', { get: () => [1, 2, 3, 4, 5] });
    Object.defineProperty(navigator, 'languages', { get: () => ['pt-BR', 'pt', 'en-US', 'en'] });
  });

  let status: number | null = null;
  let headers: Record<string, string> = {};
  let erro: string | undefined;

  try {
    const response = await page.goto(loginUrl, { waitUntil: 'domcontentloaded', timeout: 30000 });
    status = response?.status() ?? null;
    headers = response?.headers() ?? {};
  } catch (e) {
    erro = (e as Error).message;
  }

  const urlFinal = page.url();
  const title = await page.title().catch(() => '');
  const bodyTrecho = await page
    .evaluate(() => (document.body?.innerText || '').slice(0, 500))
    .catch(() => '');

  let temBtnSso = false;
  try {
    await page.waitForSelector('#btnSsoPdpj', { state: 'visible', timeout: 10000 });
    temBtnSso = true;
  } catch {
    // não achou — não é erro fatal aqui
  }

  // Detectar bloqueio (mesma lógica do trt-auth.service)
  const tituloLow = title.toLowerCase();
  const corpoLow = bodyTrecho.toLowerCase();
  const ehBloqueio =
    tituloLow.includes('403 forbidden') ||
    tituloLow.includes('the request could not be satisfied') ||
    tituloLow.includes('access denied') ||
    corpoLow.includes('generated by cloudfront') ||
    corpoLow.includes('blocked by') ||
    corpoLow.includes('request blocked');

  // Pista de quem está bloqueando
  let origemBloqueio: string | undefined;
  if (ehBloqueio) {
    if (tituloLow.includes('the request could not be satisfied')) origemBloqueio = 'CloudFront/AWS WAF';
    else if (tituloLow.includes('403 forbidden')) origemBloqueio = '403 direto (origin/nginx)';
    else if (corpoLow.includes('cloudflare')) origemBloqueio = 'Cloudflare';
    else origemBloqueio = 'WAF não identificado';
  }

  await page.close();

  return {
    trt,
    modo,
    loginUrl,
    urlFinal,
    status,
    title,
    headers: Object.fromEntries(
      Object.entries(headers).filter(([k]) =>
        ['server', 'via', 'x-cache', 'x-amz-cf-id', 'x-amz-cf-pop', 'cf-ray', 'x-powered-by'].includes(k.toLowerCase()),
      ),
    ),
    bodyTrecho,
    temBtnSso,
    ehBloqueio,
    origemBloqueio,
    erro,
    duracaoMs: Date.now() - inicio,
  };
}

async function rodarModo(modo: 'local' | 'remoto'): Promise<ResultadoTRT[]> {
  log(`\n═══ MODO: ${modo.toUpperCase()} ═══`);

  let browser: Browser;
  if (modo === 'local') {
    browser = await chromium.launch({ headless: true });
    log('   ✅ Chromium local lançado');
  } else {
    const ws = process.env.BROWSER_WS_ENDPOINT;
    const token = process.env.BROWSER_SERVICE_TOKEN;
    if (!ws) {
      log('   ⚠️ BROWSER_WS_ENDPOINT não configurado — pulando modo remoto');
      return [];
    }
    const endpoint = token && !ws.includes(token) ? (ws.endsWith('/') ? `${ws}${token}` : `${ws}/${token}`) : ws;
    browser = await chromium.connect(endpoint, { timeout: 60000 });
    log('   ✅ Conectado ao browser remoto');
  }

  const ctx = await browser.newContext({
    viewport: { width: 1920, height: 1080 },
    userAgent:
      'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/130.0.0.0 Safari/537.36',
    locale: 'pt-BR',
    timezoneId: 'America/Sao_Paulo',
    extraHTTPHeaders: {
      Accept: 'text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,*/*;q=0.8',
      'Accept-Language': 'pt-BR,pt;q=0.9,en-US;q=0.8,en;q=0.7',
      'Accept-Encoding': 'gzip, deflate, br, zstd',
      'Sec-Ch-Ua': '"Chromium";v="130", "Google Chrome";v="130", "Not?A_Brand";v="99"',
      'Sec-Ch-Ua-Mobile': '?0',
      'Sec-Ch-Ua-Platform': '"Windows"',
      'Sec-Fetch-Dest': 'document',
      'Sec-Fetch-Mode': 'navigate',
      'Sec-Fetch-Site': 'none',
      'Sec-Fetch-User': '?1',
      'Upgrade-Insecure-Requests': '1',
    },
  });

  const resultados: ResultadoTRT[] = [];
  for (const trt of TODOS_TRTS) {
    log(`   🔍 Testando ${trt}...`);
    try {
      const r = await testarTRTNoContexto(ctx, trt, modo);
      const flag = r.temBtnSso ? '✅' : r.ehBloqueio ? '🛡️' : '❓';
      log(
        `      ${flag} ${trt} | status=${r.status} | btnSso=${r.temBtnSso} | bloq=${r.ehBloqueio}${r.origemBloqueio ? ` (${r.origemBloqueio})` : ''} | title="${r.title.slice(0, 60)}" | ${r.duracaoMs}ms`,
      );
      resultados.push(r);
    } catch (e) {
      log(`      ❌ ${trt} | erro: ${(e as Error).message}`);
      resultados.push({
        trt,
        modo,
        loginUrl: `https://pje.${trt.toLowerCase()}.jus.br/primeirograu/login.seam`,
        urlFinal: '',
        status: null,
        title: '',
        headers: {},
        bodyTrecho: '',
        temBtnSso: false,
        ehBloqueio: false,
        erro: (e as Error).message,
        duracaoMs: 0,
      });
    }
  }

  await ctx.close();
  await browser.close();
  return resultados;
}

async function main() {
  log('═══════════════════════════════════════════════════════════');
  log(`  Multi-TRT Login Diagnosis (modos: ${MODOS.join(', ')})`);
  log(`  TRTs problemáticos: ${TRTS_PROBLEMATICOS.join(', ')}`);
  log(`  TRTs controle: ${TRTS_CONTROLE.join(', ')}`);
  log('═══════════════════════════════════════════════════════════');

  const todosResultados: ResultadoTRT[] = [];
  for (const modo of MODOS) {
    const r = await rodarModo(modo);
    todosResultados.push(...r);
  }

  // Análise comparativa
  log('\n📊 RESUMO COMPARATIVO:');
  log('─'.repeat(85));
  log('TRT     | Local                        | Remoto                       | Diagnóstico');
  log('─'.repeat(85));

  for (const trt of TODOS_TRTS) {
    const local = todosResultados.find((r) => r.trt === trt && r.modo === 'local');
    const remoto = todosResultados.find((r) => r.trt === trt && r.modo === 'remoto');

    const fmt = (r?: ResultadoTRT) => {
      if (!r) return 'N/A                          ';
      const flag = r.temBtnSso ? '✅' : r.ehBloqueio ? '🛡️' : '❓';
      const txt = r.temBtnSso ? 'OK' : r.ehBloqueio ? r.origemBloqueio?.slice(0, 20) || 'BLOQ' : 'falhou';
      return `${flag} ${txt} (${r.status})`.padEnd(28);
    };

    let diagnostico = '';
    if (local?.temBtnSso && remoto?.ehBloqueio) {
      diagnostico = 'BLOQUEIO NO IP DO BROWSER REMOTO';
    } else if (local?.ehBloqueio && remoto?.ehBloqueio) {
      diagnostico = 'bloqueio em UA/headers (afeta ambos)';
    } else if (local?.temBtnSso && remoto?.temBtnSso) {
      diagnostico = 'OK em ambos';
    } else if (!local?.temBtnSso && !remoto?.temBtnSso && !local?.ehBloqueio && !remoto?.ehBloqueio) {
      diagnostico = 'tribunal possivelmente fora do ar';
    } else {
      diagnostico = 'comportamento inconsistente';
    }

    log(`${trt.padEnd(7)} | ${fmt(local)} | ${fmt(remoto)} | ${diagnostico}`);
  }

  log('─'.repeat(85));

  const arquivoRelatorio = path.join(OUTPUT_DIR, `${RUN_TS}_multi-trts_relatorio.json`);
  fs.writeFileSync(arquivoRelatorio, JSON.stringify(todosResultados, null, 2), 'utf-8');
  log(`\n💾 Relatório completo: ${arquivoRelatorio}`);
}

main().catch((err: unknown) => {
  console.error('❌ Erro fatal:', err);
  process.exit(1);
});
